version: "3.6"
services:
  pdf2svg:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: psf2svg-container
    environment:
      LC_ALL: ja_JP.UTF-8
      LANG: ja_JP.UTF-8
    volumes:
      - ./doc:/tmp
    restart: always
    tty: true
